"""Notebook → script converter, run at upload time.

Turns an uploaded ``.ipynb`` into a clean, runnable ``.py`` so the training
pod only ever executes plain Python. Replaces the old in-pod
``nbconvert + regex strip`` path, whose line-based regexes corrupted string
literals, deleted ``!pip install`` dependency information, and dropped the
bodies of ``%%time`` cells (training code included).

Guarantees:

- **String safety.** A cell that already parses as pure Python (``ast.parse``)
  is emitted byte-for-byte unchanged — a ``%`` or ``!`` inside a string can
  never be touched.
- **Magic translation, not deletion.** Cells that don't parse are transformed
  with IPython's own ``TransformerManager`` (the exact machinery Jupyter uses),
  then the resulting ``get_ipython().*`` calls are rewritten into portable
  Python: ``!pip install x`` becomes a real ``subprocess`` pip install (and the
  packages are reported), ``!wget ...`` becomes ``subprocess.run``,
  ``x = !cmd`` becomes captured output, ``%%time`` keeps its body.
- **Never ships broken code.** The final script must pass ``ast.parse`` or the
  conversion reports ``ok=False`` and the caller falls back to the old path.

Pure functions, no network, no MinIO access — safe to call from a request
handler and trivially unit-testable.
"""

from __future__ import annotations

import ast
import io
import re
import shlex
import zipfile
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone

# Line magics whose argument is itself a statement worth keeping
# (`%time model.fit(X, y)` → `model.fit(X, y)`).
_LINE_MAGIC_KEEP_ARG = {"time", "timeit"}

# Cell magics whose body is plain Python that must be preserved.
_CELL_MAGIC_KEEP_BODY = {"time", "timeit", "capture", "prun"}

# Cell magics whose body is a shell script.
_CELL_MAGIC_SHELL = {"bash", "sh"}

_PIP_CMD_RE = re.compile(
    r"^\s*(?:sudo\s+)?(?:python\d*(?:\.\d+)?\s+-m\s+)?pip\d*\s+install\s+(.+)$"
)

_HEADER_TEMPLATE = """\
# ==============================================================================
# Auto-generated by the MLOps platform from: {name}
# Generated: {stamp} UTC
# Markdown cells are preserved as comments; IPython magics were translated to
# portable Python. Lines starting with "# [platform]" explain each change.
# ==============================================================================
"""

# Runtime fallback for get_ipython() calls we could not rewrite statically
# (magics nested inside if/for/def blocks). Keeps such notebooks running
# instead of crashing with NameError.
_IPYTHON_SHIM = '''\
# [platform] Minimal IPython shim: this notebook uses magics inside nested
# blocks, which cannot be rewritten statically. The shim executes them at
# runtime with plain-Python equivalents.
import os as _os, subprocess as _sp, sys as _sys


class _PlatformIPython:
    def system(self, cmd):
        _sp.run(cmd, shell=True, check=False)

    def getoutput(self, cmd, *a, **kw):
        return _sp.run(
            cmd, shell=True, capture_output=True, text=True, check=False
        ).stdout.splitlines()

    def run_line_magic(self, name, line=""):
        if name == "pip":
            _sp.run([_sys.executable, "-m", "pip", *shlex_split(line)], check=False)
        elif name == "cd":
            _os.chdir(line.strip().strip("'\\""))
        else:
            print(f"[platform] ignored IPython line magic: %{name} {line}")

    def run_cell_magic(self, name, line, cell):
        if name in ("bash", "sh"):
            _sp.run(cell, shell=True, check=False)
        elif name in ("time", "timeit", "capture", "prun"):
            exec(compile(cell, "<cell-magic>", "exec"), globals())
        else:
            print(f"[platform] ignored IPython cell magic: %%{name}")

    def magic(self, arg):
        head, _, rest = str(arg).partition(" ")
        self.run_line_magic(head.lstrip("%"), rest)


def shlex_split(s):
    import shlex as _shlex
    try:
        return _shlex.split(s)
    except ValueError:
        return s.split()


def get_ipython():
    return _PlatformIPython()
'''


@dataclass
class ConversionWarning:
    """Mirrors the analyzer's CodeWarning shape so the frontend panel can
    render both without a second component."""

    code: str
    message: str
    severity: str = "info"          # "warn" | "info"
    line_no: int | None = None      # cell number (1-based), not a line
    snippet: str | None = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ConversionResult:
    ok: bool
    script: str = ""
    warnings: list[ConversionWarning] = field(default_factory=list)
    pip_packages: list[str] = field(default_factory=list)


@dataclass
class _Ctx:
    warnings: list[ConversionWarning] = field(default_factory=list)
    pip_packages: list[str] = field(default_factory=list)
    needs_imports: bool = False     # emitted subprocess/sys/os calls
    dropped_magics: set[str] = field(default_factory=set)

    def warn(self, code: str, message: str, *, cell: int | None = None,
             severity: str = "info", snippet: str | None = None) -> None:
        self.warnings.append(ConversionWarning(
            code=code, message=message, severity=severity,
            line_no=cell, snippet=snippet,
        ))


# ── helpers ────────────────────────────────────────────────────────────────


def _comment_block(text: str, note: str = "") -> str:
    lines = []
    if note:
        lines.append(f"# [platform] {note}")
    for ln in text.splitlines():
        lines.append(f"# {ln}" if ln.strip() else "#")
    return "\n".join(lines)


def _parses(src: str) -> bool:
    # compile(), not ast.parse(): newer CPythons let ast.parse accept
    # top-level await that would still be a SyntaxError when actually run.
    try:
        compile(src, "<cell>", "exec")
        return True
    except SyntaxError:
        return False


def _has_top_level_await(src: str) -> bool:
    """True when the only thing making `src` unparseable is top-level await."""
    try:
        compile(src, "<cell>", "exec", flags=ast.PyCF_ALLOW_TOP_LEVEL_AWAIT)
        return True
    except SyntaxError:
        return False


def _match_get_ipython(call: ast.AST) -> tuple[str, list[ast.expr]] | None:
    """Return (method, args) when `call` is `get_ipython().<method>(...)`."""
    if not isinstance(call, ast.Call):
        return None
    f = call.func
    if (
        isinstance(f, ast.Attribute)
        and isinstance(f.value, ast.Call)
        and isinstance(f.value.func, ast.Name)
        and f.value.func.id == "get_ipython"
        and not f.value.args
    ):
        return f.attr, call.args
    return None


def _const_str(node: ast.expr) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def _pip_install_args(cmd: str) -> list[str] | None:
    """If `cmd` is a pip install command, return the tokens after `install`."""
    m = _PIP_CMD_RE.match(cmd.strip())
    if not m:
        return None
    try:
        return shlex.split(m.group(1))
    except ValueError:
        return m.group(1).split()


def _pip_rewrite(args: list[str], ctx: _Ctx, cell_no: int) -> str:
    ctx.needs_imports = True
    ctx.pip_packages.extend(t for t in args if not t.startswith("-"))
    ctx.warn(
        "pip_install_converted",
        f"`pip install {' '.join(args)}` from the notebook will run inside the "
        f"training pod before the rest of the cell.",
        cell=cell_no,
        snippet=" ".join(args)[:80],
    )
    arg_list = ", ".join(repr(a) for a in args)
    return (
        f"subprocess.check_call([sys.executable, '-m', 'pip', 'install', {arg_list}])"
        f"  # [platform] from notebook !pip install"
    )


# ── per-statement rewrite of the transformed cell ──────────────────────────


def _rewrite_statement(stmt: ast.stmt, src: str, ctx: _Ctx, cell_no: int) -> str:
    """Rewrite one top-level statement of a TransformerManager-transformed cell.

    Returns replacement source; falls back to the original segment when the
    statement contains no get_ipython() call we know how to translate.
    """
    segment = ast.get_source_segment(src, stmt) or ""

    # x = !cmd  →  x = get_ipython().getoutput('cmd')
    if isinstance(stmt, ast.Assign):
        matched = _match_get_ipython(stmt.value)
        if matched and matched[0] == "getoutput" and matched[1]:
            target = " = ".join(ast.unparse(t) for t in stmt.targets)
            cmd_expr = ast.unparse(matched[1][0])
            ctx.needs_imports = True
            return (
                f"{target} = subprocess.run({cmd_expr}, shell=True, "
                f"capture_output=True, text=True).stdout.splitlines()"
                f"  # [platform] from notebook `= !cmd`"
            )
        return segment

    if not isinstance(stmt, ast.Expr):
        return segment

    matched = _match_get_ipython(stmt.value)
    if not matched:
        return segment
    method, args = matched

    if method == "system" and args:
        cmd = _const_str(args[0])
        if cmd is not None:
            pip_args = _pip_install_args(cmd)
            if pip_args is not None:
                return _pip_rewrite(pip_args, ctx, cell_no)
            ctx.needs_imports = True
            ctx.warn(
                "shell_command_converted",
                f"Shell command `!{cmd}` will run with subprocess inside the pod.",
                cell=cell_no, snippet=cmd[:80],
            )
            return (
                f"subprocess.run({cmd!r}, shell=True, check=False)"
                f"  # [platform] from notebook !command"
            )
        # dynamic: !{something computed}
        ctx.needs_imports = True
        return (
            f"subprocess.run({ast.unparse(args[0])}, shell=True, check=False)"
            f"  # [platform] from notebook !command"
        )

    if method == "getoutput" and args:
        ctx.needs_imports = True
        return (
            f"subprocess.run({ast.unparse(args[0])}, shell=True, "
            f"capture_output=True, text=True)"
            f"  # [platform] from notebook !command (output unused)"
        )

    if method in ("run_line_magic", "magic") and args:
        if method == "magic":
            raw = _const_str(args[0]) or ""
            name, _, line = raw.lstrip("%").partition(" ")
        else:
            name = _const_str(args[0]) or ""
            line = (_const_str(args[1]) if len(args) > 1 else "") or ""

        if name == "pip":
            pip_args = _pip_install_args(f"pip {line}")
            if pip_args is not None:
                return _pip_rewrite(pip_args, ctx, cell_no)
        if name == "cd" and line.strip():
            ctx.needs_imports = True
            return (
                f"os.chdir({line.strip().strip(chr(39) + chr(34))!r})"
                f"  # [platform] from notebook %cd"
            )
        if name == "env" and line.strip():
            if "=" in line:
                key, _, val = line.partition("=")
            else:
                key, _, val = line.partition(" ")
            if key.strip() and val.strip():
                ctx.needs_imports = True
                return (
                    f"os.environ[{key.strip()!r}] = {val.strip()!r}"
                    f"  # [platform] from notebook %env"
                )
        if name in _LINE_MAGIC_KEEP_ARG and line.strip() and _parses(line):
            ctx.warn(
                "timing_magic_unwrapped",
                f"`%{name}` timing removed; the timed statement itself is kept.",
                cell=cell_no,
            )
            return f"{line}  # [platform] %{name} removed, statement kept"
        # anything else: display/environment magic → comment out
        ctx.dropped_magics.add(f"%{name}")
        return f"# [platform] IPython magic removed: %{name} {line}".rstrip()

    if method == "run_cell_magic" and len(args) >= 3:
        name = _const_str(args[0]) or ""
        line = _const_str(args[1]) or ""
        body = _const_str(args[2]) or ""

        if name in _CELL_MAGIC_KEEP_BODY:
            ctx.warn(
                "cell_magic_body_kept",
                f"`%%{name}` removed but the cell body is kept and will run.",
                cell=cell_no,
            )
            converted_body = _convert_code_cell(body, cell_no, ctx, depth=1)
            return f"# [platform] %%{name} removed, body kept\n{converted_body}"

        if name in _CELL_MAGIC_SHELL:
            ctx.needs_imports = True
            ctx.warn(
                "shell_cell_converted",
                f"`%%{name}` cell will run as a shell script via subprocess.",
                cell=cell_no,
            )
            return (
                f"subprocess.run({body!r}, shell=True, check=False)"
                f"  # [platform] from notebook %%{name} cell"
            )

        if name == "writefile":
            tokens = line.split()
            append = "-a" in tokens
            fname_tokens = [t for t in tokens if not t.startswith("-")]
            if fname_tokens:
                fname = fname_tokens[0].strip("'\"")
                mode = "a" if append else "w"
                ctx.warn(
                    "writefile_converted",
                    f"`%%writefile {fname}` converted to a real file write.",
                    cell=cell_no, snippet=fname,
                )
                return (
                    f"with open({fname!r}, {mode!r}, encoding='utf-8') as _pf:"
                    f"  # [platform] from %%writefile\n"
                    f"    _pf.write({body!r})"
                )

        # display-only or unknown cell magic (html, javascript, sql, ...)
        ctx.warn(
            "cell_magic_commented",
            f"`%%{name}` cell is not Python and was commented out.",
            cell=cell_no, severity="warn", snippet=f"%%{name}",
        )
        return _comment_block(
            f"%%{name} {line}\n{body}".rstrip(),
            note=f"cell magic %%{name} commented out (not runnable as a script)",
        )

    return segment


def _transform_with_ipython(src: str) -> str | None:
    """Run IPython's canonical cell transformer; None when unavailable/failing."""
    try:
        from IPython.core.inputtransformer2 import TransformerManager
    except Exception:  # pragma: no cover - environment without IPython
        return None
    try:
        return TransformerManager().transform_cell(src)
    except Exception:
        return None


def _convert_code_cell(src: str, cell_no: int, ctx: _Ctx, depth: int = 0) -> str:
    """Convert one code cell's source into runnable plain Python."""
    src = src.rstrip("\n")
    if not src.strip():
        return ""

    # Fast path: already valid Python — emit unchanged. This is the
    # string-safety guarantee: nothing inspects individual lines.
    if _parses(src):
        return src

    if _has_top_level_await(src):
        ctx.warn(
            "top_level_await",
            "Cell uses top-level `await`, which only works inside a notebook. "
            "Wrap it in `asyncio.run(...)`; the cell was commented out.",
            cell=cell_no, severity="warn",
        )
        return _comment_block(src, note="cell uses top-level await; commented out")

    if depth > 2:  # defensive recursion cap for nested cell magics
        return _comment_block(src, note="nested cell magic too deep; commented out")

    transformed = _transform_with_ipython(src)
    if transformed is None or not _parses(transformed):
        ctx.warn(
            "cell_syntax_error",
            f"Cell {cell_no} has a syntax error and was commented out. "
            "Fix it in the notebook and re-upload.",
            cell=cell_no, severity="warn",
        )
        skipped = _comment_block(src, note=f"cell {cell_no} skipped (syntax error)")
        return (
            f"print('[platform] WARNING: notebook cell {cell_no} was skipped "
            f"(syntax error)')\n{skipped}"
        )

    tree = ast.parse(transformed)
    pieces = [
        _rewrite_statement(stmt, transformed, ctx, cell_no) for stmt in tree.body
    ]
    return "\n".join(p for p in pieces if p != "")


# ── public API ─────────────────────────────────────────────────────────────


def convert_notebook_bytes(data: bytes, original_name: str) -> ConversionResult:
    """Convert a notebook's raw bytes into a runnable Python script."""
    ctx = _Ctx()

    try:
        import nbformat
    except Exception:  # pragma: no cover - deps missing on the server
        ctx.warn("converter_unavailable",
                 "Server is missing nbformat/IPython; notebook will be "
                 "converted inside the training pod instead.", severity="warn")
        return ConversionResult(ok=False, warnings=ctx.warnings)

    try:
        nb = nbformat.reads(data.decode("utf-8"), as_version=4)
    except Exception as exc:
        ctx.warn("notebook_unreadable",
                 f"Could not parse the notebook: {type(exc).__name__}: {exc}",
                 severity="warn")
        return ConversionResult(ok=False, warnings=ctx.warnings)

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    parts: list[str] = [_HEADER_TEMPLATE.format(name=original_name, stamp=stamp)]
    code_cells = 0

    for idx, cell in enumerate(nb.get("cells", []), start=1):
        ctype = cell.get("cell_type")
        src = cell.get("source", "")
        if isinstance(src, list):
            src = "".join(src)

        if ctype == "markdown":
            if src.strip():
                parts.append(f"# --- Cell {idx} (markdown) " + "-" * 40)
                parts.append(_comment_block(src))
            continue
        if ctype != "code" or not src.strip():
            continue

        code_cells += 1
        parts.append(f"# === Cell {idx} " + "=" * 48)
        parts.append(_convert_code_cell(src, idx, ctx))

    if code_cells == 0:
        ctx.warn("empty_notebook",
                 "Notebook contains no executable code cells.", severity="warn")

    if ctx.dropped_magics:
        names = ", ".join(sorted(ctx.dropped_magics))
        ctx.warn("line_magics_removed",
                 f"Notebook-only magics removed (harmless outside Jupyter): {names}.")

    body = "\n\n".join(p for p in parts if p.strip())

    preamble: list[str] = []
    if "get_ipython(" in body:
        preamble.append(_IPYTHON_SHIM)
        ctx.warn(
            "nested_magics_shimmed",
            "Some magics sit inside if/for/def blocks; a runtime shim executes "
            "them with plain-Python equivalents.",
        )
    if ctx.needs_imports:
        preamble.append(
            "import os, subprocess, sys  # [platform] injected for converted "
            "notebook commands"
        )

    script = "\n\n".join([*preamble, body]) + "\n"

    # Final gate: never ship a syntactically broken script. compile(), not
    # ast.parse() — see _parses().
    try:
        compile(script, "<converted>", "exec")
    except SyntaxError as exc:
        ctx.warn(
            "conversion_failed",
            f"Converted script failed to parse (line {exc.lineno}: {exc.msg}); "
            "falling back to in-pod conversion.",
            severity="warn",
        )
        return ConversionResult(ok=False, warnings=ctx.warnings,
                                pip_packages=sorted(set(ctx.pip_packages)))

    return ConversionResult(
        ok=True,
        script=script,
        warnings=ctx.warnings,
        pip_packages=sorted(set(ctx.pip_packages)),
    )


def convert_notebooks_in_zip(data: bytes) -> tuple[bytes, list[dict]]:
    """Add a converted ``.py`` beside every notebook inside a zip archive.

    Returns ``(zip_bytes, conversions)``; the original bytes come back
    untouched when the zip is invalid or contains no notebooks.
    """
    try:
        zin = zipfile.ZipFile(io.BytesIO(data))
    except zipfile.BadZipFile:
        return data, []

    names = set(zin.namelist())
    notebooks = [
        n for n in zin.namelist()
        if n.lower().endswith(".ipynb")
        and ".ipynb_checkpoints" not in n
        and "__MACOSX" not in n
        and not n.rsplit("/", 1)[-1].startswith("._")
    ]
    if not notebooks:
        return data, []

    out = io.BytesIO()
    conversions: list[dict] = []
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            zout.writestr(item, zin.read(item.filename))
        for nb_name in notebooks:
            result = convert_notebook_bytes(
                zin.read(nb_name), nb_name.rsplit("/", 1)[-1]
            )
            stem = nb_name[: -len(".ipynb")]
            target = f"{stem}.py" if f"{stem}.py" not in names else f"{stem}_converted.py"
            if result.ok:
                zout.writestr(target, result.script)
            conversions.append({
                "original": nb_name,
                "script": target if result.ok else None,
                "ok": result.ok,
                "warnings": [w.to_dict() for w in result.warnings],
                "pip_packages": result.pip_packages,
            })
    return out.getvalue(), conversions
