FROM python:3.11-slim

RUN pip install --no-cache-dir \
    boto3==1.35.81 \
    mlflow==2.11.0 \
    scikit-learn==1.5.2 \
    pandas==2.2.3 \
    joblib==1.4.2 \
    nbconvert==7.16.4 \
    ipython==8.26.0 \
    numpy \
    matplotlib \
    seaborn \
    xgboost \
    lightgbm

WORKDIR /workspace
